<script type="text/javascript" src="<?=js_url()?>/jquery.min.js"></script>
<script type="text/javascript" src="<?=js_url()?>/ddsmoothmenu.js"></script>
<script type="text/javascript" src="<?=js_url()?>/menu.js"></script>
<script type="text/javascript" src="<?=js_url()?>/contentslider.js"></script>
<script type="text/javascript" src="<?=js_url()?>/jquery.1.4.2.js"></script>
<script type="text/javascript" src="<?=js_url()?>/jquery.lint.js"></script>
<script type="text/javascript" src="<?=js_url()?>/jquery.scroll.js"></script>
<script type="text/javascript" src="<?=js_url()?>/scroll.js"></script>
<script type="text/javascript" src="<?=js_url()?>/jquery.idTabs.min.js"></script>
<script type="text/javascript" src="<?=js_url()?>/switch.js"></script>
<script type="text/javascript" src="<?=js_url()?>/tabs.js"></script>
<script type="text/javascript" src="<?=js_url()?>/cufon-yui.js"></script>
<script type="text/javascript" src="<?=js_url()?>/cufon.js"></script>
<script type="text/javascript" src="<?=js_url()?>/Myriad_Pro_400-Myriad_Pro_700-Myriad_Pro_italic_400-Myriad_Pro_italic_700.font.js"></script>